# Generated by Django 4.1.2 on 2022-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('due_date', models.DateField()),
                ('assigned_to', models.CharField(max_length=20)),
            ],
        ),
    ]
